<?php
$page->addScript('js/jquery-1.8.2.js');
$page->addScript('js/textify.js');
$page->addScript('js/jquery.easing.1.3.js');
$page->addCss('css/textify.css');

$id = $controller -> getParam(1);
	$db->query("SELECT
		p.id,
        p.name,
        m.caption,
        cpd.photo,
        cpd.short_des,
        cpd.link,
        cpd.full_des
        FROM
        cat_prod_des AS cpd,
        prod AS p
        INNER JOIN menu AS m ON p.id_razd = m.id
        WHERE
        p.showCat = 1
        AND
        cpd.prod_id = p.id");
	$products = $db->getArray();
	foreach ($products as $product) {
			if($product['id']==$id){
				$des = $product['full_des'];
					$descr = preg_replace('/\n{3,}/','', $des);
			        $descr =str_replace("\n", '<br />',  $descr);
			        $descr =str_replace("<h2>", '<span class="h2">',  $descr); 
			        $descr =str_replace("</h2>", '</span>',  $descr);
			        $prev = 'product/show/'.$product['link'];
			        ?>
			        <script type="text/javascript">
	$(document).ready(function(){
		$('.text_page').textify({
		numberOfColumn: 2,
		margin: 50,
		padding: 0,
		width: "auto",
		height: "auto", 
		showNavigation: true,
		textAlign: 'left'
		});

		}) 
</script>        
			        <div class="wrap">

				    <div class="main_page">
				        <div class="f_l head_red"><?php echo $product['caption'];?></div>
				        <div class="f_r num_page">
			        	<?php
			        		foreach ($_SESSION['idPage'] as $cont) {
								if($cont['id']==$id) {echo $cont['page']."<span>a</span>";
                                    $curPage = $cont['page'];}
							}
			        	?>
				        </div>
				        <div class="clear"></div>
				        <div class="title"><span><?php echo $product['name'];?></span></div>

				        <div class="f_l ">
				            <p class="text_page marg_more text_page_more"><?php echo $descr;?></p>
				        </div>




				        <div class="clear"></div>
				        <a href="<?php echo $prev ?>" class="mar_0_auto bt bt_more_back">Вернуться к товару</a>
				    </div>
				    <a class=" left_ar"> </a>
				    <a class="right_ar"></a>
				    <?php }}?>
					</div>
<?php
			if($curPage == count($_SESSION['idPage'])+2){
		    	$link = "content";		    	
		    }else{

		    	$next_id = $_SESSION['idPage'][$curPage+1]['id'];
		    	$db ->query("SELECT link FROM cat_prod_des WHERE prod_id = {$next_id}");
		    	$link = $db->getValue();
		    	$link = "product/show/".$link;
		    	
		    }
		    echo '<input type="hidden" id="next" value="'.$link.'"/>';
		    echo '<input type="hidden" id="prev" value="'.$prev.'"/>';
		    ?>

		

