<?php
	$year=date("Y",time());
	// $param=$controller->getURI();
	// if(!empty($param[0]))
	// {
		$left_main="class='left'";
		$right_main="class='right'";
		echo "	</div> <!-- main -->";
	// }
	// else
	// {
	// 	$left_main="class='left_main'";
	// 	$right_main="class='right_main'";
		
	// }
	
			echo "
			<div class='clear'></div>
			<div id='footer'>
                <div class='one'></div>
                <div class='two'></div>
                <div class='three'></div>
                <div ".$right_main.">
                    GEA © $year
                </div>
                <div ".$left_main.">";
                    //<!--+38 063 376 32 48<br />
                    //+38 050 680 90 72<br />
					//+79671201265<br />-->
                   echo " biznes@gealtd.org<br />    
                    doktor@gealtd.org  ";
                  //<!--  <br />
                   // echo "email: 777angel2@rambler.ru-->
                echo "</div>
            </div>
		</div> <!-- wrapper -->";
    echo "</div> <!-- background-right -->";
    echo "</div> <!-- background-left -->";
?>