
<?php
    //header('Location /');
    $page->setTitle("GEA | Руководство");
	$page->setKeywords("Руководство");
    echo "<div class='nav'><a href='/about/'>Компания</a></div>";
    echo "<div class='productCaption'>Руководство</div>";
?>
<!--<p align="center" style="color: red; font:bold 30px arial">Страница находиться в разработке</p>-->
<div class="management-block">
    <div class="management-block-photo"><img src="/img/management/1.png"/></div>
    <div class="management-block-text">
        <div class="management-block-text-name">ГНЕТНЕВА<br/>Елена<br/>Алексеевна</div>
        <div class="management-block-text-who">Президент<br/>Компании</div>
    </div>
</div>

<div class="management-block">
    <div class="management-block-photo"><img src="/img/management/3.jpg"/></div>
    <div class="management-block-text">
        <div class="management-block-text-name">
            РАСТОРГУЕВА<br/>Лилия<br/>Михайловна</div>
        <div class="management-block-text-who">Советник Компании<br/>по информационному обеспечению.</div>
    </div>
</div>

<div class="management-block">
    <div class="management-block-photo"><img src="/img/management/2.jpg"/></div>
    <div class="management-block-text">
        <div class="management-block-text-name">
            ГАНАЧКОВА<br/>Татьяна<br/>Юрьевна</div>
        <div class="management-block-text-who">Советник Компании<br/>по региональному развитию.</div>
    </div>
</div>
<div class="management-block">
    <div class="management-block-photo"><img src="/img/management/4.jpg"/></div>
    <div class="management-block-text">
        <div class="management-block-text-name">
            ГОЛОВЧЕНКО<br/>Александр<br/>Эдуардович</div>
        <div class="management-block-text-who">Советник Компании<br/>по стратегическому развитию.</div>
    </div>
</div>

 
<div class="clear"></div>