<?php
    $page->setTitle("GEA | Внимание");
    
    echo "<div class='productCaption'>Внимание!</div>
            <p>Компания GEA Group работает только с оригинальной продукцией (поставки непосредственно от производителя). <span class='bold'>Вся продукция защищена</span>  изображением Торговой марки Компании<!--<sup>&reg;</sup>-->, что <span class='bold red'>гарантирует ее высокое качество</span>.</p>
            <div class='hologram'>
               <img src='img/logo_(TM).png' alt='hologram' width='169'>
            </div>";
?>
<div class="docBlock">
    <img src="img/svidoctvo1.png" alt="certificate">
    <div class="clear"></div>
    <a class="cert-more" href="img/svidoctvo1Big.png" target="_blank" ><span>Подробнее</span></a>
</div>
<div class="docBlock2">
    <img src="img/svidoctvo2.png" alt="certificate">
    <div class="clear"></div>
    
</div>  

<div class="docBlock2text">
        Свидетельство<br />о регистрации<br />TM ООО &laquo;ГЕА Групп&raquo;
</div>
<div class="clear"></div>
