<?php
    $page->setTitle("GEA | Главная");
    $page->addScript("jquery.cookie.min.js, jquery.timers.min.js, main.js");

?>
<div style="position:relative;width: 400px;height: 40px;padding:12px 0;background: url('../img/main_back_news.png');margin: -240px auto 0 auto;text-align: center;color:#FFF;border-radius: 5px;font: bold 26px/34px verdana; ">

        <a href="https://catalog.gealtd.org" style="color:#fff">Электронный каталог</a>
    </div>
    <!--<div style="margin: 0 auto;width:798px;height: 339px;margin-top: 266px;left:50%;">
        <img src="/img/HB-Dolbus.png" />
    </div>-->
    
    <!--<div style="margin: 0 auto;height: 100px;margin-top: 55%;">
    <div id='mainEventsBlock' style="width:322px;">
        <div class='mainEvent first'>
        <div class='img' style='background-image: url(img/sss.png);'></div>
        <div class='text' style='top: 17px; left: 135px;'>Новый<br />промоушен</div>
        <a class='more' href='/events/'><span style=''>Подробнее</span></a>
        </div> 
    </div>
    </div>-->

    <?php
       
    //$page->keywords = "gea group, gea компания, китайская медицина, лечение китайской медициной, изофлавоны, удаление избыточного веса, очищение кровеносных сосудов, оздоровительные тампоны";

  /*  echo "  <div id='mainEventsBlock' style='margin-top:540px;'>
            <div class='mainEvent first'>
                    <div class='img' style='background-image: url(img/main/akciya-prodolj.png);'></div>
                    <div class='text' style='top: 17px; left: 135px;'>Акция к открытию<br /> Компании!!!</div>
               
                    <a class='more' href='56'><span style=''>Подробнее</span></a>

                </div>
                
                <div class='mainEvent mainEventLast'>
                    <div class='img' style='background-image: url(img/youtube.png); margin-top:-5px;'></div>
                    <div class='text' style='top: 17px; left: 135px;'>Смотирите видео<br />на YouTube</div>
                    <a class='more2' href='http://www.youtube.com/user/gealtd'><span style=''>Подробнее</span></a>
                </div>
            </div>
            <div class='clear'></div>";*/
            
?>
<!--img/prokladki_min.png href='51'
	<div class='img' style='background-image: url(img/youtube.png); margin-top:-5px;'></div>
                    <div class='text' style='top: 17px; left: 135px;'>Смотирите видео<br />на YouTube</div>
                    <a class='more2' href='http://www.youtube.com/user/gealtd'><span style=''>Подробнее</span></a>-->

<?php
if (date("G") >= 17) 
{
    $img = 'bNigth.jpg';
    $back = '#193258';
}
else 
{
    if (date("G") < 5)
    {
        $img = 'bNigth.jpg';
        $back = '#193258';
    } 
    else
    {
        $img = 'bDay.jpg';
        $back = '#EFCD9F';
    }
}

 
?>
<script type='text/javascript'>
function calculateRatio()
{
$('body').css('overflow-x','hidden');
    $('body').css('overflow-y','hidden');
    var w=$(window).width();
    var h=$(window).height();
    if ((w<=800 && h<=480)&&(typeof(window.ontouchstart) == 'undefined')) return false;
    else 
    {
        var wImg = $('#imgBack').width();
        var imgLeft = -parseInt((wImg - w) / 2);
        //console.log(h)
        //$('.slider').width(w).height(h);    
        if(w / h > (16/9)) 
        {
            $('#imgBack').css({height:parseInt(((w / 16) * 9) + 10),width:parseInt(w),marginLeft:0});
            $('#wrapper').css('min-height',parseInt(h) - 90 + 'px');
        }
        else 
        {
            $('#imgBack').css({width:(parseInt((h / 9) * 16)),height:parseInt(h),marginLeft:imgLeft})
            $('#wrapper').css('min-height',parseInt(h) - 90  + 'px');
        } 
    }
    //var delta = $('#wrapper').height() - $(window).height();
    //if (delta > 0) $('#wrapper').css('min-height',$('#wrapper').height() -delta+'px');
    //$('html').height($('html').height()-10)
    $('body').height($('body').height()-10)

}
$(document).ready(function(){
window.onmousewheel = document.onmousewheel = window.onscroll = document.onscroll = function (e) {return false;};
//$('#main_back').width($(window).width()).css('overflow','hidden')
$('#main_back').append('<img id="imgBack" style="min-width:1000px;width:100%;position:absolute;top:-10px;" src="../img/main_back_new.jpg"/>');//min-width:960px;
calculateRatio()
//$('*').live('mousemove keydown scroll',function(){
//    calculateRatio()
//})
//$('*').css('overflow-x','hidden')
 


});  

//$('body').css('background-color','#555');
//$('body').css('background-color','<?php echo $back?>');
    var width=$(window).width();
    var w=width/3.9;
    var h=w*1.3;
    if(width>=1700)
    {
$("#m1900").css('margin-top','-19%');
    //	$('#mainEventsBlock').css('margin-top',(h+180)+'px');//
	//	$('#mainEventsBlock').css('margin-left',w);
    }
	else 
	{
	//	$('#mainEventsBlock').css('margin-top','400px');//333px
	//	$('#mainEventsBlock').css('margin-left','190px');
	}


 $(window).resize(function(){ 
    //project()   
    calculateRatio()
    // отодвигает главную часть от меню
	 var width=$(window).width();
	var w=width/3.9;
    var h=w*1.3;
	if(width>=1000)
    {
    	//$('#mainEventsBlock').css('margin-top',(h+180)+'px');//
	//	$('#mainEventsBlock').css('margin-left',w);
    }
	else //false;
    	{
		//$('#mainEventsBlock').css('margin-top','400px');//333px
		//$('#mainEventsBlock').css('margin-left','190px');
	}
     //project();
   
})




function project(){
    if($(window).width()>=1800)
    {	$('#mainEventsBlock').css('margin-top',(h+600)+'px');} 
    
        if (($(window).width()>=1450)&&($(window).width()<1800))
    {	$('#mainEventsBlock').css('margin-top',(h+450)+'px');} 
    
    
     if($(window).width()<1123) {
    $('#project').css('font-size','22px');
    $('#project').css('width','40%');
}
else{
$('#project').css('font-size','30px');
$('#project').css('width','44%');}
}

//if ($('#startday').val()>0)
   // {
    //if (($('#startday').val()==6)||($('#startday').val()==5)) dat='дней';
     //   else if (($('#startday').val()==4)||($('#startday').val()==3)||($('#startday').val()==2)) dat='дня';
     //       else if ($('#startday').val()==1) dat='день';
    
   // $('#project_day').html($('#startday').val()+' '+dat);
   // }
   // else 
   // {$('#project').css('z-index','-10');}

</script>

</div>