<!--<a class='cert-back' href='#'><span>Вернуться к товару</span></a>-->
<div class='productCaption'>Паразиты, глисты, гельминты</div>
<div class='parasites'>
	<table>
	<tr>
		<td><img src="img/parasites/lambl1.jpg" alt="лямблии" align="bottom"/>Простейшие паразиты: лямблии</td>
		<td><img src="img/parasites/lambl2.jpg" alt="лямблии" align="bottom"/>Простейшие паразиты: лямблии</td>
	</tr>
	<tr>
		<td><img src="img/parasites/ascarid1.jpg" alt="аскариды" align="bottom"/>Глисты нематоды: аскариды</td>
		<td><img src="img/parasites/ascarid2.jpg" alt="анизакиды" align="bottom"/>Глисты нематоды: анизакиды</td>
	</tr>
	<tr>
		<td><img src="img/parasites/scepen1.jpg" alt="бычий цепень" align="bottom"/>Глисты цестоды: бычий цепень</td>
		<td><img src="img/parasites/scepen2.jpg" alt="свиной цепень" align="bottom"/>Глисты цестоды: свиной цепень</td>
	</tr>
	<tr>
		<td><img src="img/parasites/opistorh.gif" alt="описторхоз" align="bottom"/>Глисты трематоды: описторхоз</td>
		<td><img src="img/parasites/toksokar1.jpg" alt="токсокары" align="bottom"/>Глисты нематоды: токсокары</td>
	</tr>
	<tr>
		<td><img src="img/parasites/toksokar2.jpg" alt="головка токсокары" align="bottom"/>Головка токсокары</td>
		<td><img src="img/parasites/toksokar3.jpg" alt="токсокара в глазу" align="bottom"/>Токсокара в глазу</td>
	</tr>
	<tr>
		<td><img src="img/parasites/ankil1.jpg" alt="анкилостома" align="bottom"/>Глисты нематоды: анкилостома</td>
		<td><img src="img/parasites/ankil2.jpg" alt="головка анкилоскомы" align="bottom"/>Головка анкилостомы</td>
	</tr>
	<tr>
		<td><img src="img/parasites/vlasogl.jpg" alt="личинки анизакида" align="bottom"/>Личинки анизакид в печени сайды</td>
		<td><img src="img/parasites/ehinokok.jpg" alt="эхиноккок" align="bottom"/>Глисты цестоды: эхиноккок</td>
	</tr>
	<tr>
		<td><img src="img/parasites/parazit1.jpg" alt="паразиты на зубах" align="bottom"/>Паразиты на зубах</td>
		<td><img src="img/parasites/parazit2.jpg" alt="аскариды в сердце" align="bottom"/>Аскариды в сердце</td>
	</tr>
	<tr>
		<td><img src="img/parasites/parazit3.jpg" alt="пораженный мозг" align="bottom"/>Пораженный паразитами мозг</td>
		<td><img src="img/parasites/parazit5.jpg" alt="широкий лентец" align="bottom"/>Широкий лентец</td>
	</tr>
	</table>
</div>