<?php $root=$_SERVER['DOCUMENT_ROOT'];?>
<?php require_once $root.'/editor/menu.php'?>
<style>

</style>

<script>
    $(document).ready(function(){(function($) {
  $.fn.wrapSelected = function(open, close) {
    return this.each(function() {
      var textarea = $(this);
      var value = textarea.val();
      var start = textarea[0].selectionStart;
      var end = textarea[0].selectionEnd;
      if (value.substring(start, end)!=0)
      textarea.val(
        value.substr(0, start) + 
        open + value.substring(start, end) + close + 
        value.substring(end, value.length)
      );
    });
  };
})(jQuery);
        $('input[name="save"]').live('click',function(){//return false;
            if ($('input[name="date"]').val()=='') {$('input[name="date"]').css('border','solid red 2px');return false;}
                else {$('input[name="date"]').css('border','');}
            if ($('input[name="title"]').val()=='') {$('input[name="title"]').css('border','solid red 2px');return false;}
                else $('input[name="title"]').css('border','');
            if ($('textarea[name="desc"]').val()=='') {$('textarea[name="desc"]').css('border','solid red 2px');return false;}
                else $('textarea[name="desc"]').css('border','');
        })
    
    
$("#b").live('click',function(){$("textarea").wrapSelected("<b>", "</b>");return false;})
$("#i").live('click',function(){$("textarea").wrapSelected("<i>", "</i>");return false;})
function insert_text_cursor(_obj_name, _text)
// _obj_name - name объекта - как правило, textarea, но при желании можно сделать любой
// указываем именно NAME, так как согласно стандартам DOCTYPE HTML 4.01 strict и выше
// свойство ID у объектов ввода является не приемлемым и требуется обращаться только name
// _text - текст, который требуется вставить в том место, где сейчас находится курсор
{
// берем объект
var area=document.getElementsByName(_obj_name).item(0);

// Mozilla и другие НОРМАЛЬНЫЕ браузеры
if ((area.selectionStart)||(area.selectionStart=='0'))
{ // определяем, где начало выделения, если оно существует
  var p_start=area.selectionStart;

  // определяем, где заканчивается выдедение, если оно существует
  var p_end=area.selectionEnd;

  // вставляем соответствующий текст в указанное место
  area.value=area.value.substring(0,p_start)+_text+area.value.substring(p_end,area.value.length);
}

// Исправляем очередной геморрой с Internet Explorer
// единственный НЕ человеческий браузер
if (document.selection)// если объект может иметь выделения
{ // передаем фокус ввода на нужный нам объект
  area.focus();

  // узнаем выделение, если оно существует 
  sel=document.selection.createRange();

  // вставляет текст в указанное место
  sel.text=_text;
}
}// end function
$("#l").live('click',function(){
var y=prompt('Введите URL','http://');
if (y.substr(8,1))
{
   y2=y.substr(7);
    insert_text_cursor('desc', ' <a target="_blank" href="'+y+'">'+y2+'</a> ');
}

return false;
})
    
        
    })
</script>

<script language="JavaScript">
document.onkeydown = checkKeycode
function checkKeycode(e) {
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
if (keycode==116) {return false}
}
</script>

<!-- Удаление -->

<?php
if ($_GET['del'])
{
    $img=mysql_fetch_array(mysql_query("select img from event where id={$_GET['del']}"));
    @unlink($root.'/img/event/'.$img['img']);
    mysql_query("delete from event where id={$_GET['del']}");
    echo '<div class="down">';
    echo '<span class="green">Событие удалено.</span>';
    echo '</div>';
}
?>





<!-- Удаление картинки-->

<?php
if ($_GET['delimg'])
{
    $img=mysql_fetch_array(mysql_query("select img from event where id={$_GET['delimg']}"));
    @unlink($root.'/img/event/'.$img['img']);
    mysql_query("update event set img='' where id={$_GET['delimg']}");
    echo '<div class="down">';
    echo '<span class="green">Картинка удалена.</span>';
    echo '</div>';
}
?>









<!-- Добавление -->

<?php
if ($_POST['add'])
{
    echo '<form method="POST" action="event.php" enctype="multipart/form-data" name="edit"><div class="down"><b>Добавление</b><br /><br />';
        echo 'Дата: <input id="date" style="width:700px;float:right;margin-right:30px" name="date" type="text" value="'.date('Y-m-d').'"/><br /><br />';
        echo 'Введите заголовок: <input style="width:700px;float:right;margin-right:30px" type="text" name="title" value=""/><br /><br />';
        echo 'Описание: <textarea name="desc" style="width:700px;float:right;margin-right:30px;height:400px"></textarea><br /><br />';
        
                echo '  <button id="i" title="Курсив" onclick="return false"><i style="font-family: times new roman;">I</i></button>
                <button id="b" title="Жирный"><b>B</b></button> 
                <button id="l" title="Cсылка">URL</button>';
        
        echo '<div style="clear:both"></div>';
        echo 'Фото: <input  type="file" accept="image/jpeg" name="img" style="width:700px;float:right;margin-right:30px"><br /><br />';
        echo '<div style="clear:both"></div>';
        echo '<input type="submit" name="save" value="Сохранить" />';
    echo'</div></form>';
}
?>










<!-- Редактирование -->

<?php
if ($_GET['edit'])
{
    echo '<style>.td-'.$_GET['edit'].'{background:silver;color:red;} .td-'.$_GET['edit'].' a{color:red}</style>';
    $edit=mysql_fetch_array(mysql_query("select * from event where id={$_GET['edit']}"));
    echo '<form method="POST" action="event.php" enctype="multipart/form-data" name="edit"><div class="down"><b>Редактирование</b><br /><br />';
        echo 'Дата: <input id="date" style="width:700px;float:right;margin-right:30px" name="date" type="text" value="'.$edit['date'].'"/><br /><br />';
        echo 'Введите заголовок: <input style="width:700px;float:right;margin-right:30px" type="text" name="title" value="'.$edit['title'].'"/><br /><br />';
        echo 'Описание: <textarea name="desc" style="width:700px;float:right;margin-right:30px;height:400px">'.$edit['desc'].'</textarea><br /><br />';
        
        echo '  <button id="i" title="Курсив" onclick="return false"><i style="font-family: times new roman;">I</i></button>
                <button id="b" title="Жирный"><b>B</b></button> 
                <button id="l" title="Cсылка">URL</button>';
        
        echo '<div style="clear:both"></div>';
        echo 'Фото: <input  type="file" accept="image/jpeg" name="img" style="width:700px;float:right;margin-right:30px"><br /><br />';
        echo '<div style="clear:both"></div>';
        echo '<input type="hidden" name="id" value="'.$_GET['edit'].'"><br /><br />';
        echo '<input type="submit" name="save" value="Сохранить" />';
    echo'</div></form>';
}
?>




<!-- Обработка инфы -->

<?php
if ($_POST['save'])
{   
    echo '<div class="down">';
    if ($_POST['id'])
    {
            $img=mysql_fetch_array(mysql_query("select img from event where id={$_POST['id']}"));
            
            $_POST['desc'] = str_replace("'", "\'", $_POST['desc']);
            $_POST['desc'] = str_replace("`", "&lsquo;", $_POST['desc']);
            $_POST['desc'] = str_replace('"', "\"", $_POST['desc']);
            
            if (mysql_query("update event set date='".$_POST['date']."', title='".$_POST['title']."', `desc`='".$_POST['desc']."' where id=".$_POST['id'])) echo '<span class="green">Событие успешно изменено.</span><br />'; 
                else echo '<span class="red">Error. Событие не было измененно!</span><br />';
                
            if ($_FILES['img']['tmp_name'])
            {
                $imginfo=getimagesize($_FILES['img']['tmp_name']);
               // print_r($imginfo);
                if ($imginfo[0]<100) {echo '<span class="red">Error. Картинка меньше 100px по ширине!</span><br />';}
                else 
                {
                    if (!$img['img']) 
                    {
                        $imgname=uniqid().'.jpg';
                        mysql_query("update event set `img`='".$imgname."' where id={$_POST['id']}");
                        $img=mysql_fetch_array(mysql_query("select img from event where id={$_POST['id']}"));
                    }
                    if (!(move_uploaded_file($_FILES['img']['tmp_name'], $root.'/img/event/'.$img['img'])))
                        {echo '<span class="red">Error. Картинка не загружена!</span><br />';}
                    else {echo '<span class="green">Картинка загружена успешно.</span><br />'; }
                    
                    if ($imginfo[0]>=351)
                    {
                        echo '<span class="green"> Картинка была уменьшена до 350px по ширине!</span><br />';
                        resize($root.'/img/event/'.$img['img'], $root.'/img/event/'.$img['img'], 350, false);
                    }
            
                }
                
            }
    }
    else
    {
     //   print_r($_POST);
   // print_r($_FILES['img']);
        $imgname=uniqid().'.jpg';
        if ($_FILES['img']['tmp_name'])
        {
            $imginfo=getimagesize($_FILES['img']['tmp_name']);
            if ($imginfo[0]<100) {echo '<span class="red">Error. Картинка меньше 100px по ширине!</span><br />';}
            else
            {
                if (!(move_uploaded_file($_FILES['img']['tmp_name'], $root.'/img/event/'.$imgname)))
                {     
                    echo '<span class="red">Error. Картинка не загружена!</span>';
                }
                else 
                {
                    if ($imginfo[0]>=760)
                    {
                        echo '<span class="green">Картинка была уменьшена до 700px по ширине!</span><br />';
                        resize($root.'/img/event/'.$imgname, $root.'/img/event/'.$imgname, 700, false);
                    }
                    echo '<span class="green">Картинка загружена успешно.</span>'; 
                }
                
            }
         }
         $_POST['desc'] = str_replace("'", "\'", $_POST['desc']);
         //$_POST['desc'] = str_replace("`", "&lsquo;", $_POST['desc']);
         $_POST['desc'] = str_replace('"', "\"", $_POST['desc']);
         if ($_FILES['img']['tmp_name'])
            {if (mysql_query("INSERT INTO  `event` (`date`, `title` ,`desc`, `img`) VALUES ('{$_POST['date']}', '{$_POST['title']}', '{$_POST['desc']}', '{$imgname}')")) echo '<span class="green">Новое событие было записано успешно.</span><br />'; 
            else echo '<span class="red">Error. Событие не было сохранено!</span>';}
            else
            {if (mysql_query("INSERT INTO  `event` (`date`, `title` ,`desc`) VALUES ('{$_POST['date']}', '{$_POST['title']}', '{$_POST['desc']}')")) echo '<span class="green">Новое событие было записано успешно.</span><br />'; 
            else echo '<span class="red">Error. Событие не было сохранено!</span>';}           
        
    }
    echo '</div>';
}
?>








<table>
    <thead>
        <tr>
            <td>№</td>
            <td>Дата</td>
            <td>Заголовок</td>
            <td>Описание</td>
            <td>Картинка</td>
            <td>Изменить</td>
            <td>Удалить</td>
        </tr>
    </thead>
    <?php
    $q=mysql_query("select * from event order by date desc");
    while ($e=mysql_fetch_array($q))
    {
    echo '<tr>';
        echo '<td class="td-'.$e['id'].'">'.(++$n).'</td>';
        echo '<td class="td-'.$e['id'].'">'.datefromsql($e['date']).'</td>';
        echo '<td class="td-'.$e['id'].'">'.$e['title'].'</td>';
        echo '<td class="td-'.$e['id'].'" style="text-align:center"><a class="preview" title="'.strip_tags($e['desc']).'"><img style="cursor:pointer" src="/img/map.png" /></a></td>';
        echo '<td class="td-'.$e['id'].'" style="text-align:center">'; 
            if ($e['img'])
                echo '<a href="/img/event/'.$e['img'].'" class="preview" onclick="return false"><img src="/img/event/'.$e['img'].'" height="30px"/></a><a href="event.php?delimg='.$e['id'].'" style="position: absolute;margin: -7px 0 0 5px;" title="Удалить картинку"><span class="red" style="font-size:20px">&times;</span></a>';
            else echo '<img src="/img/no-img.png" title="Нет фото" />';
       //     $text=strip_tags($e['desc']);
            
            //$text=iconv("utf8", "windows-1251", $text);
            
       //     if (strlen($text)>180)  $text=substr($text, 0, strrpos(substr($text, 0, 180), ' ')).' ...' ; else $text=$text;
       //     echo $text;
       //     echo iconv("windows-1251", "utf8", $text); 
        echo '</td>';
        echo '<td class="td-'.$e['id'].'"><a href="'.$url.'?edit='.$e['id'].'">Изменить</a></td>';
        echo '<td class="td-'.$e['id'].'"><a href="'.$url.'?del='.$e['id'].'">Удалить</a></td>';
    echo '</tr>';
    }
    ?>
</table>

<div class="down" style="margin:140px auto">
    <form method="POST" action="event.php">
        <input type="submit" value="Добавить событие" name="add"/>
    </form>
</div>

<?php require_once $root.'/admin/foot.php'?>